### ISSUE TITLE
[Demo] Clickable links

### ISSUE THREAD

**Issue by o-sdn-o** [netxs-group/VTM#11]
If some link is displayed in the multiplexer, it would be nice to allow it to be opened by clicking on it.

- [ ] Make URLs clickable
  Open links in a new multiplexer window
- [ ] Design link preview
  URL highlighting functionality

Link types
- Path
  Shell instance in new multiplexer window
- URL
  New multiplexer window with content

**Comment by netxs-group** [comment]
At the moment, the main task is to publish for testing the first release of the desktop environment with the functionality of launching common terminal shells/applications by users. The meaning of the issue may change radically.
