### ISSUE TITLE
Japanese characters don't wrap correctly on window title

### ISSUE THREAD

**Issue by kerunaru** [netxs-group/vtm#117]
Here the title is correct, showing the character "Ｃ".

<img width="560" alt="Captura de pantalla 2021-08-23 a las 18 32 25" src="https://user-images.githubusercontent.com/94023/130483891-70ec0af0-be14-4bc7-bf71-8701ea020648.png">

Here is corrupted.

<img width="590" alt="Captura de pantalla 2021-08-23 a las 18 28 41" src="https://user-images.githubusercontent.com/94023/130483478-3bad94de-45a3-494b-b9c0-4d0a8c44947b.png">

I recall japanese characters are bigger than ASCII ones… Could it be vtm is splitting the character without considering this?

**Comment by o-sdn-o** [comment]
At this point, vtm wraps text strings cell by cell, so any wide characters are split in half.  These are CJK, Emoji and all other wide Unicode characters.  The problem will be resolved with the hyphenation module (it is not ready yet).  This will allow wrap graphemes (and words) without splitting in half.

**Comment by o-sdn-o** [comment]
Since no terminal is yet able to display halves of wide characters, they are displayed with a placeholder

**Comment by o-sdn-o** [comment]
Related discussion https://github.com/microsoft/terminal/issues/4345

**Comment by o-sdn-o** [comment]
![image](https://user-images.githubusercontent.com/11535558/130587778-74745f4e-0fd2-48ab-a34f-64ebcf238c28.png)

**Comment by o-sdn-o** [comment]
So far, I've only solved this issue with window titles. The built-in terminal still cuts wide characters in half when wrapping.

**Comment by o-sdn-o** [comment]
This functionality is available in [v0.5.9999](https://github.com/netxs-group/vtm/releases/tag/v0.5.9999).
