### ISSUE TITLE
linux console and gpm

### ISSUE THREAD

**Issue by jocutajar** [netxs-group/vtm#125]
I've noticed that running vtm on the linux console and with gpm doesn't quite work. Is it meant to? Would it be difficult to support? Or am I doing something wrong? It seems that GPM mouse events are simply ignored. I'm not sure if I can achieve anything without a mouse there.

**Comment by o-sdn-o** [comment]
Linux console requires RW access to the `/dev/input/mice` meta device:
```
sudo chmod 666 /dev/input/mice
```
GPM is not used, vtm writes init  codes and reads mouse events directly to/from `/dev/input/mice`.

**Comment by o-sdn-o** [comment]
Also for the Linux console It is necessary to set TERM=linux

**Comment by o-sdn-o** [comment]
There are several limitations when working in the linux console:
- The mouse will not work when connecting to vtm remotely from the linux console, the remote vtm does not have access to local `/dev/input/mice` and GPM doesn't support xterm-style mouse reporting. A workaround is to use a locally launched vtm for remote connections.
- Only a mouse that supports the `imps2 (ImPS/2 Generic Wheel Mouse)` protocol works in vtm, but it seems to me that now all mice support it.

If your mouse doesn't work, write me your mouse model and I will add support for the protocol it uses.

**Comment by o-sdn-o** [comment]
GPM interferes with vtm. To use the mouse in vtm in the Linux console, GPM must be disabled or uninstalled.

**Comment by jocutajar** [comment]
Thanks for your excellent support. I got it working with disabling the GPM and adding my user to the `input` group + login again.

```
$ ls -la /dev/input/mice 
crw-rw---- 1 root input 13, 63 Nov  2 23:58 /dev/input/mice
```
I didn't like making the mice world writeable so I chose the more conservative approach.

**Comment by o-sdn-o** [comment]
> adding my user to the input group

This approach opens read/write access to the keyboard device for all processes running on behalf of your user.

You can restrict access only to the mouse device, but for this you need to create a separate device node. I added an option to vtm so that it tries to open not only `/dev/input/mice`, but also `/dev/input/mice_vtm`. I will make this option configurable in the future.

```bash
#!/bin/bash
# Create a separate mice device node and allow users to access it.

# Group for allowed users.
sudo groupadd vtm

# Script for node init.
sudo cat <<EOF > /etc/udev/rules.d/mice_vtm.sh
#!/bin/bash
mice=/dev/input/mice_vtm
# See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/devices.txt
mknod --mode=660 $mice c 13 63
chown root:vtm $mice
EOF

# Script run rule.
sudo echo 'SUBSYSTEM=="input", KERNEL=="mice", RUN+="/etc/udev/rules.d/mice_vtm.sh"' > /etc/udev/rules.d/85-mice_vtm.rules

# Trigger udev to reload rules
sudo udevadm control --reload-rules && devadm trigger


# Adding user to the vtm group
#sudo usermod -a -G vtm user_name
```

**Comment by klamonte** [comment]
I see you mentioned GPM having unsolvable problems on Reddit.  Can you mention what can't work?  I'm just curious to try it out and see. :-)  My [GPM code is here](https://gitlab.com/klamonte/lcxterm/-/blob/master/source/input.c#L1640), but a bit messy: I directly adapted it from ncurses mouse model (where I have to track all the buttons to know what to release later), and could probably simplify it a lot.

**Comment by o-sdn-o** [comment]
I don’t remember it exactly, and I didn’t document it, but offhand there were such problems:

- There seems to be incorrect processing of the ImPS/2 protocol when scrolling the wheel quickly, `|wheel delta| > 1` is interpreted as horizontal scrolling. No wheel reports if  `|wheel delta| > 2`.
   See https://github.com/telmich/gpm/blob/e82d1a653ca94aa4ed12441424da6ce780b1e530/src/mice.c#L664-L681
- Sometimes mouse wheel events are not supported at all  (apparently the wrong mouse port mode is being used for my mouse model that I tested on)
- And of course direct gpm dependency itself

I was also very confused by [this issue](https://github.com/telmich/gpm/issues/29), I thought that I should not rely on gpm at all.

**Comment by klamonte** [comment]
Thank you!

> And of course direct gpm dependency itself

That's a good point too.  I couldn't build on Alpine Linux for a while because their gpm package didn't install correctly, and somehow no one noticed before me.  (It's fixed now.)
