### ISSUE TITLE
Support custom 16-color palette

### ISSUE THREAD

**Issue by tomek-szczesny** [netxs-group/vtm#132]
Most Linux terminals support at least 16-color palette (including THE linux console). The actual colors in this palette may be redefined freely from full 24-bit palette using appropriate escape sequences, and using websites that aid this process, such as [terminal.sexy](https://terminal.sexy/).

There are many programs using only 16-color palette, such as vim, mc, tmux. Amost anything based on curses..

Since vtm uses full color palette internally, it has some sort of defaults specified for that 16-color palette. I don't like them. Blue is too dark and I can barely see anything when redshift activates.

I have my terminal configured with better suited colors for my needs. Unfortunately, as far as I'm aware, software has no way of reading these settings back from the terminal, not without terminal-specific hacks.

The best solution I could think of is letting a user define 16-color palette in vtm settings.
Even better, vtm could scan .bashrc for any terminal color changing mechanisms and learn these settings, as this is by far the most usual place to apply them. Alas, this is not failproof and would probably need a lot of work.

Some time ago I tried helping with virtual terminal implementation for [notcurses](https://www.youtube.com/watch?v=dcjkezf1ARY), that's where I learned this and that about terminals. Unfortunately I proved myself, yet again, that I'm not fluent enough in programming to be of any actual help.

**Comment by o-sdn-o** [comment]
Thanks for your suggestions, I fully support them. There must be a way to configure colors.

The following color schemes must be supported:
- [ ] Color scheme of the vtm itself (UI)
- [ ] Color scheme for each built-in application separately
- [ ] Configurable color palette of 16/256 colors in the built-in terminal

The first two schemes require external storage of settings, this will be implemented together with the implementation of the settings subsystem.

The third scheme depends on the terminal runtime and the palette can be changed using escape sequences emitted at the start of the shell during the terminal startup.

I know of two vt-sequences for changing the existing 16/256 color palette
1. `ESC` ] 4 ; \<i\> ; rgb:\<r\>/\<g\>/\<b\> `BEL`
   (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands)
2. `ESC` ] P `nrrggbb`
   (https://man7.org/linux/man-pages/man4/console_codes.4.html) Set palette, with parameter given in 7 hexadecimal digits after the final P :-(. Here n is the color (0-15), and rrggbb indicates the red/green/blue values ​​(0-255). ESC] R: reset palette...

I am implementing support for the first vt-sequence (OSC 4) for the built-in terminal. The second sequence (OSC P) breaks the OSC, and it seems to me that it only exists to support legacy.

**Comment by tomek-szczesny** [comment]
I'm glad you like my suggestion.

The typical sequence for changing terminal colors looks like the following (it has been generated by terminal.sexy):
```
#!/bin/sh
if [ "$TERM" = "linux" ]; then
  /bin/echo -e "
  \e]P0282a2e
  \e]P1a54242
  \e]P28c9440
  \e]P3de935f
  \e]P45f819d
  \e]P585678f
  \e]P65e8d87
  \e]P7707880
  \e]P8373b41
  \e]P9cc6666
  \e]PAb5bd68
  \e]PBf0c674
  \e]PC81a2be
  \e]PDb294bb
  \e]PE8abeb7
  \e]PFc5c8c6
  "
  # get rid of artifacts
  clear
fi
```

As I said before, it is usually pasted into .bashrc or called from there. I don't think this is obsolete.
What exactly is the problem with implementing that? Why OSC P breaks OSC? 

Anyway, if built-in terminal accepts either of these two formats (ideally both), and it executes .bashrc on start (which bash itself probably does), I think the problem would be resolved.

**Comment by o-sdn-o** [comment]
I have implemented support for OSC P. So far, this is in the `dev/sdn` branch. I will update the master branch and make the binaries then I finish OSC 4.

Note: In order to see the changes after changing the palette, you will need to reprint the entire contents of the terminal, since all output is converted to truecolor on output and is no longer associated with the palette.

**Comment by o-sdn-o** [comment]
Also vtm has a fixed 8+8 color palette for Linux console mode ($TERM=linux).  In this mode, there are only four colors and four shades of gray.  In this mode, the palette of the built-in terminal does not matter, since the conversion to four colors occurs directly when the frame is rendered in the physical Linux console.

In this case, I haven't figured out what to do yet.

**Comment by o-sdn-o** [comment]
The 8+8 color palette is the palette with 8 background and 16 foreground colors. It is specific to the linux console due to the VGA text mode buffer limits.

**Comment by tomek-szczesny** [comment]
You are the man! :D Thank you!

> Note: In order to see the changes after changing the palette, you will need to reprint the entire contents of the terminal, since all output is converted to truecolor on output and is no longer associated with the palette.

I see, and no way to refresh this. Perhaps SIGWINCH could be sent to a program currently running in terminal to force it to redraw itself?


> Also vtm has a fixed 8+8 color palette for Linux console mode ($TERM=linux). In this mode, there are only four colors and four shades of gray. In this mode, the palette of the built-in terminal does not matter, since the conversion to four colors occurs directly when the frame is rendered in the physical Linux console.
> 
> In this case, I haven't figured out what to do yet.

In "linux" term I think most users have already set up their favorite colors using bash scripts, like the one I posted somewhere above. In this case I believe linux terminal always tries to find the nearest match from what is available, if a color from 24-bit space is requested. I think I read about it somewhere, but I am not 100% sure.
The point is, the closest match is found based on the palette currently in use, and not the default hardcoded one.
This is especially important if someone has set up a weird palette with nonstandard colors for any reason.

Anyway, if this is true, then I think vtm should be fed the same 8+8 palette information by the user, to keep the output consistent. I don't think there is much more to do on your side.

I'll be happy to test this branch in the following days and try to come up with a reasonable solution. :)

**Comment by o-sdn-o** [comment]
> I see, and no way to refresh this. Perhaps SIGWINCH could be sent to a program currently running in terminal to force it to redraw itself?

Thanks for the tip! If there are such applications that first draw themselves, and then change the palette, then we will have to do so. There is one nuance here: When setting the entire palette (OSC P), after each color change there will be a complete redrawing. It will probably be very expensive even for 16 colors. If such applications come across, then I will experiment with it.

**Comment by tomek-szczesny** [comment]
Yeah, I wouldn't worry about this just yet. Allow me to test that `sdn` branch and see how it performs, perhaps implementing `OSC P` and `OSC 4` was all we need, after all. :)

**Comment by tomek-szczesny** [comment]
![2021-12-07-150519_1492x234_scrot](https://user-images.githubusercontent.com/44300715/145043610-251e8297-64ca-44bf-bda8-73d80c1460ad.png)

I think it works perfectly, at least in civilized terminal. :)
On the left there are default colors. 
On the right, I invoked another terminal, but after pasting `OSC P` based configuration into `.bashrc`.

I'll see how it behaves in `linux` terminal later. :)

**Comment by tomek-szczesny** [comment]
Okay, there is something wrong.

As a reference I use a script available [here](https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh).

I also have some palette specified in .bashrc:

```
[mctom@Tomusiomat ~]$ tail -n 20 .bashrc


    echo -en "\e]P0000000" #black
    echo -en "\e]P8555753" #darkgrey
    echo -en "\e]P1970000" #darkred
    echo -en "\e]P9FB1A1A" #red
    echo -en "\e]P2549502" #darkgreen
    echo -en "\e]PA6FE100" #green
    echo -en "\e]P3967805" #brown
    echo -en "\e]PBE0CA1A" #yellow
    echo -en "\e]P40054C1" #darkblue
    echo -en "\e]PC5996FF" #blue
    echo -en "\e]P565178A" #darkmagenta
    echo -en "\e]PDD336C2" #magenta
    echo -en "\e]P6027A67" #darkcyan
    echo -en "\e]PE6CC2C2" #cyan
    echo -en "\e]P79DA496" #lightgrey
    echo -en "\e]PFEEEEEC" #white

    clear
```

Here is the output in uxterm, natively and in vtm. The native output is the perfect one, what is supposed to be.

![2021-12-07-194856_801x157_scrot](https://user-images.githubusercontent.com/44300715/145089266-5858a8c4-1dd0-4210-8ed9-6bd24de34dfc.png)
![2021-12-07-195033_847x227_scrot](https://user-images.githubusercontent.com/44300715/145089280-e0623b0b-deff-495b-add4-1836e63205e5.png)

Here are the same outputs in urxvt, native and from vtm.
It does seem like urxvt attempts some sort of color dithering, but it's not important. the point is that is a 256 color terminal.

![2021-12-07-195641_1215x152_scrot](https://user-images.githubusercontent.com/44300715/145089552-7c257fd3-e09e-4b4d-a43b-9589f455addc.png)
![2021-12-07-195659_1206x226_scrot](https://user-images.githubusercontent.com/44300715/145089569-016ca60b-5c25-44ac-a396-16033675737b.png)

And finally, here is the output in linux console, native and in vtm:
![IMG_20211207_193154](https://user-images.githubusercontent.com/44300715/145090093-003fe381-63ad-4d0a-8053-00d14a63ca90.jpg)
![IMG_20211207_193227](https://user-images.githubusercontent.com/44300715/145090108-5d560d0a-5339-4509-b95d-40cf5c379124.jpg)


Even though I use synthetic test for all that, the effect is the same with tmux or mc.

Here are my conclusions:
- vtm renders proper colors in 256-color terminals, but not in full color, or in Linux console
- vtm output in Linux console looks just like in 24-bit terminal

Hm. I wonder if vtm has a problem parsing input, or emitting output in this case.

**Comment by o-sdn-o** [comment]
Apparently the problem here is that vtm seems to incorrectly determine the capabilities of the terminal in which it is running. It determines capabilities using the $TERM variable

https://github.com/netxs-group/vtm/blob/3652688cd39d105496325e7d54a2ff46263c0c18/src/netxs/os/system.hpp#L288-L299

Additionally, 16 colors terminals are all that end with `16color` and `16colour` in $TERM.

If VTM determines only 16 colors, then it operates in 8+8 colors mode.

**Comment by o-sdn-o** [comment]
In 8+8 color mode vtm uses fixed 16-color palette. When outputting, vtm selects the closest color within its palette. For background colors, only the first 8 colors are used.

Fixed 8+8 palette:
https://github.com/netxs-group/vtm/blob/3652688cd39d105496325e7d54a2ff46263c0c18/src/netxs/ui/layout.hpp#L364-L382

**Comment by o-sdn-o** [comment]
I removed `tmux` and `xterm` from the list of 16 color terminals.

**Comment by tomek-szczesny** [comment]
Well, my little experiment shows it's best to just send full color data regardless of terminal capabilities. Even `linux` console handles that well. Was there any particular reason to implement this? Anyway in this case I'd simply remove `linux` off the 16-color terminal list, as it does the conversion itself.

Perhaps `terminfo` could be useful to determine terminal capabilities? It has an impressive database already. 

The terminals that I use:
```
TERM=xterm
TERM=rxvt-unicode-256color
TERM=linux
```
`uxterm` is just an unicode variant of `xterm`, so it introduces itself the same. Both are full color terminals, and certainly not 16 color.
`tmux` is 256 color, last time I checked. :)

Anyway, even if the detection is not working properly, I think there is still something wrong with the conversion.

> Fixed 8+8 palette:

I find this palette very strange. It has 6 shades of gray, and right next to each other. if 16-color mode means using CSI 38 and 48 to change foreground and background, this is not what they expect. [This](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) is the correct palette, I think.

But nevertheless, since users may alter the default palette and we have no way of knowing it, I think conversion to 3/4-bit palette should be avoided.

**Comment by o-sdn-o** [comment]
> Was there any particular reason to implement this?

All elements of the user interface are blended together without using such a palette. This number of shades of gray is due to the need to highlight the window against the background, the focused window against the normal window, the mouse highlight against the focused window. + White color and shaded white color for displaying scrollbars.

![image](https://user-images.githubusercontent.com/11535558/145110514-43d3b2bc-c8ce-410e-b8c1-147afe627489.png)

![image](https://user-images.githubusercontent.com/11535558/145111813-accba172-99ff-4813-a74a-3d06cabdfdc3.png)

**Comment by o-sdn-o** [comment]
The main reason is that the entire UI is drawn with color and not with characters. I tried to find some balance, and it turned out like this.

**Comment by tomek-szczesny** [comment]
Ah, I see. So in fact, in 16 color terminals you take the liberty to define the palette yourself. This is why using the user defined palette is not going to work.

**Comment by tomek-szczesny** [comment]
Could you help me find that piece of code that converts rgb color into 16-color?

I still can't understand why results were so bizzare in my case. Only fully saturated red and blue got translated properly, the rest is gray.

**Comment by o-sdn-o** [comment]
> Could you help me find that piece of code that converts rgb color into 16-color?

Foreground and background colors are calculated differently (8 bg colors, 16 fg colors) 
https://github.com/netxs-group/vtm/blob/5888d251eb5186e2c42b8ee400925293b986e2ac/src/netxs/console/ansi.hpp#L457-L532

Grayscaling
https://github.com/netxs-group/vtm/blob/5888d251eb5186e2c42b8ee400925293b986e2ac/src/netxs/ui/layout.hpp#L176-L182

**Comment by o-sdn-o** [comment]
> Only fully saturated red and blue got translated properly, the rest is gray.

All colors are converted to grayscale, with the exception of blue and red, as they highlight menu items with some blur. UI elements lose their clear outline unless the blur around them is converted to grayscale.

**Comment by o-sdn-o** [comment]
Honestly, I myself have forgotten how the vtm converts color, now I'm diving into it 😁

**Comment by o-sdn-o** [comment]
The main problem is the limitation of 8 background colors in the Linux console. It looks acceptable only using a grayscale.

**Comment by o-sdn-o** [comment]
It probably makes sense to make a choice of color (tone) for grayscaling in the settings.

**Comment by tomek-szczesny** [comment]
Yeah, I think the point of all this is to preserve "usability" with linux console, but not necessarily make it pretty if it's just unfeasible. 
Now I think this is not crucial to let users modify this internal palette. It is just so vtm can be used in case of emergency. :)

Perhaps a startup warning would make sense, to indicate that 16-color terminal has been detected, thus everything might look a bit out of place (and "don't show me this again").

Or, even better. Since there is no hope you will ever make a complete database of all terminals and their capabilities, and terminfo is a bit clunky in use (not my opinion, just heard that somewhere), a color test could be done. User could be presented with color patterns and asked if they look the same or not. Not great for people with impaired vision, but otherwise would let the end user select color mode for an exotic terminal on their own.
That's just a loose idea for the future, if the problem proves itself widespread.

And lesson learned, linux console is inexcusably poor. ;) I wasn't aware background colors were limited to 8, but it does appear so even in my tests above.

Thank you for all that, you explained more to me than I was able to suggest in return :)
xterm works okay now, thanks for the fix. :)

So, in terms of the original issue, I think this is solved. terminal app supports my preferred palette stored in .bashrc and it looks perfect. It may be closed, unless you feel like I could be of any further assistance in the subject.

**Comment by o-sdn-o** [comment]
You are right, the 8+8 mode was originally planned as an emergency mode and there are not even any optimization during the output.

Great, thank you very much for your attention and testing vtm. It turned out great. I also think that everything is solved with this issue and I am closing this issue. 👌
