### ISSUE TITLE
[Term] Lines/block selection by mouse

### ISSUE THREAD

**Issue by o-sdn-o** [netxs-group/vtm#149]
## Selecting text in terminal

- Select text using `LeftDrag`
- Double `LeftClick` to select a word
  - Select emails by clicking on `@` character
  - Select numbers, IP-addresses or any kind of numerical stuff by clicking on digits
  - Select whitespace by clicking on `whitespace` character
  - Select a `word` by clicking on any letter
- Triple `LeftClick` to select the entire paragraph
- Switch to block (rectangular) selection by holding the `Alt` key
- Append selection by holding the `Ctrl` key
- Dismiss selection using `LeftClick`
- Copy selection using `RightClick` (+`Ctrl` to keep selection visible after copy)
- Paste copied data using `RightClick`
- Render clipboard content around mouse cursor
- Clear local clipboard buffer using `Left+RightClick` anywhere
- Modify selection by dragging markers
- Change the style of the selected lines with the UI toggles ` =─   ─=─   ─= `  `Wrap`
- Copy mode toggle button (three states; takes precedence over mouse tracking mode):
  - No selection available
      ```diff
      # Selection #
      ```
  - Select text only (plain text, default)
      ```diff
      + Plaintext +
      ```
  - Select text with all attributes (ANSI-escaping: colors, alignment, etc)
      ```diff
      ! ANSI-text !
      ```
- Status info bottom left
  - Block selection:  `h_size : v_size`
  - Linear selection:  `n rows ~m cells`
- Scrolling region `DECSTBM` aware

**Comment by o-sdn-o** [comment]
Mouse selection for alternate buffer:

https://user-images.githubusercontent.com/11535558/154154724-bf9ad088-a258-40ed-8b3e-a91af65da59b.mp4

**Comment by o-sdn-o** [comment]
Selecting text like a word processor (scrollback buffer)

https://user-images.githubusercontent.com/11535558/155153088-0af6743b-2786-4d49-9882-8e4db07e1438.mp4

**Comment by UltraStudioLTD** [comment]
I have a **few** questions.
1. Why is your project not so well-known? I mean this project is greater than many other alternatives and even those alternatives are well-known.
2. How did you learn things like this
3. Are you really human and not some kind of Terminal god/deity or whatever?!

**Comment by o-sdn-o** [comment]
> Why is your project not so well-known?

vtm is just starting to become usable. Until recently, it was just a demo. But even now it has several serious drawbacks that do not allow it to be used in production.
- Built-in terminal is very memory hungry. But his greed can be tempered by about 30 times, See #147
- Embedded terminal can only run in main process space, not as a standalone process, and memory is not reallocated when it is closed, See #148
- Cannot be operated with keyboard only, See #86

> How did you learn things like this

The field of terminal/console applications includes many different subject areas
- [Unicode Standard (latest)](http://www.unicode.org/versions/latest/), [About the Unicode](https://unicode.org/standard/standard.html). It is important to read it and understand it. It is one of the fundamental things.
- [Character encodings](https://en.wikipedia.org/wiki/Character_encoding) in particular [UTF-8](https://en.wikipedia.org/wiki/UTF-8), but also historical encodings you need to know to understand the subject.
- Font technologies are also fundamental. [Font Wikipedia](https://en.wikipedia.org/wiki/Font). A comprehensive description of this technology can be found in the [FontForge documentation](https://fontforge.org/en-US/documentation/). There is also a lot of information on fonts in the documentation of various SDKs, for example [Win32 Fonts](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-fonts).
- [Writing systems](https://en.wikipedia.org/wiki/List_of_writing_systems). Key writing systems for understanding key principles:
  - [Logographic writing systems](https://en.wikipedia.org/wiki/Logogram) (e.g. Chinese characters)
  - True alphabets (e.g. Latin/Cyrillic)
  - [Abugidas](https://en.wikipedia.org/wiki/Abugida) (e.g. Devanagari)
  - [Right-to-left scripts](https://en.wikipedia.org/wiki/Right-to-left_script) (e.g. Arabic, Hebrew)
- History and principles of operation of terminals, as well as many IT-standards associated with it.
- Basic knowledge of operating systems [POSIX(Unix)](https://en.wikipedia.org/wiki/POSIX) and Microsoft Windows (Win32)
- Some knowledge of Algebra and Mathematical analysis (mainly for video FX, but not only)
- Well, programming itself in the most general sense of the word 🙂

>Are you really human?

My youtube [channel](https://www.youtube.com/user/sdn19790)  😎✌

**Comment by o-sdn-o** [comment]
Modify the style of the selected lines

https://user-images.githubusercontent.com/11535558/163689873-db46472a-a310-4458-8807-e1a67e0e2f90.mp4

**Comment by o-sdn-o** [comment]
- Render copied content around mouse cursor
- Clear local clipboard buffer using `Left+RightClick` anywhere
- Paste copied data using `RightClick`

https://user-images.githubusercontent.com/11535558/164500213-6a33ff78-c92e-4faf-ba70-f7ecdbe99a75.mp4

**Comment by UltraStudioLTD** [comment]
> * Render copied content around mouse cursor
> * Clear local clipboard buffer using `Left+RightClick` anywhere
> * Paste copied data using `RightClick`
> 
>  Terminal.Dev.2022-04-21.20-31-09.mp4

Better make it optional or create some kind of shortcut which enables/disables that behavior.

**Comment by UltraStudioLTD** [comment]
Since big content will cover huge amount of space

**Comment by UltraStudioLTD** [comment]
Or just add preview shortcut, meaning that while holding preview shortcut button it will temporarily show copied buffer

**Comment by o-sdn-o** [comment]
Oooh, thanks for discussing this feature design.
This design is due to the fact that you must always see the contents of the clipboard, since it can be modified by external sources.

Insзired by https://gitlab.gnome.org/GNOME/vte/-/issues/2495

If at some point it needs to be removed, then it can be instantly reset with a `left+right` click.

Also the preview is limited to a field of 80x25.

**Comment by o-sdn-o** [comment]
I have never used such a feature. I need to see how practical (and safe) it is. In the future, this can be configured in the settings. It's just not yet clear which settings are needed.

**Comment by o-sdn-o** [comment]
I will now publish release 0.7.0 in which this feature will be hardcoded, and in subsequent releases I will make corrections based on the experience gained.

**Comment by o-sdn-o** [comment]
Feel free to continue the discussion here.

**Comment by UltraStudioLTD** [comment]
I will test it later and will make feedback about it's practicality

**Comment by o-sdn-o** [comment]
I also updated the release to 0.7.1, in which I removed the side indents (three cells on the left and right). Initially, I thought it was convenient, but now I realized that it is not.

**Comment by UltraStudioLTD** [comment]
I have a question. How to build DEMO version?

**Comment by UltraStudioLTD** [comment]
I use Termux currently so I can't use releases version due architecture difference (aarch64 is mine, while releases are amd64)

**Comment by o-sdn-o** [comment]
> I have a question. How to build DEMO version?

You should uncomment `//#define DEMO` in `vtm.cpp`

**Comment by UltraStudioLTD** [comment]
Are there any flags needed during cmake build?

**Comment by o-sdn-o** [comment]
> Are there any flags needed during cmake build?

In some cases it is necessary to set the `CMAKE_BUILD_TYPE=Release`

**Comment by UltraStudioLTD** [comment]
Alright I will try

**Comment by o-sdn-o** [comment]
I decided to completely abandon the grips. They don't make sense. The user can hold down the Ctrl key to modify the selection and there is no need to hit the grip exactly. I am working on it now.

**Comment by o-sdn-o** [comment]
Get rid of grips (by holding `Ctrl` key)

https://user-images.githubusercontent.com/11535558/164816461-780c89cf-0d4a-4ba7-8381-8e3bb3794594.mp4
