### ISSUE TITLE
Can't install vtm

### ISSUE THREAD

**Issue by WarpWing** [netxs-group/vtm#172]
Hey all, I've been having this issue where it's missing a dependencies called "rich-text". Any idea on how to fix?
![image](https://user-images.githubusercontent.com/28925758/152880994-d952879e-1845-456b-bc8e-7f024b285b27.png)
It's on the `--build` stage

**Comment by o-sdn-o** [comment]
It's like the C++ compiler you're using doesn't support std::span from the C++20 standard.

**Comment by o-sdn-o** [comment]
Updating the C++ compiler will most likely solve this problem.

**Comment by o-sdn-o** [comment]
Tell me what OS you are using and I will try to find a way to update the compiler on this system.

**Comment by WarpWing** [comment]
> Tell me what OS you are using and I will try to find a way to update the compiler on this system.

Thanks for the reply! I currently use Ubuntu 20.04.3. My g++ compiler is currently at 9.3.0
![image](https://user-images.githubusercontent.com/28925758/152895934-2c08eca6-3282-4d04-8134-504fecd44607.png)

**Comment by o-sdn-o** [comment]
By default Ubuntu 20.04 repositories provide GCC version 9.3.0.
std::span requires GCC 10 or higher.

The default Ubuntu repositories include several GCC versions, from 7.x.x to 10.x.x.
Install the latest GCC and G++ versions by typing:
```bash
sudo apt update
sudo apt install gcc-10 g++-10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
```

**Comment by 19noam** [comment]
Download the binary file (`https://github.com/netxs-group/vtm/releases/latest/download/vtm_linux_amd64.tar.gz`) extract the `vtm_linux_amd64.tar.gz` and move the binary file to `/bin`

**Comment by o-sdn-o** [comment]
> I was wondering how exactly I can acquire extra apps besides the default ones?

Unfortunately, these are just mock-ups for applications, including the desktopio store itself, this is a mock-up for demonstrating the capabilities of the desktopio UI framework.

The goal of the whole project (Desktopio Framework) is to make such applications real 🙂.

**Comment by Vosjedev** [comment]
i have the same issue. tried
```
sudo apt update
sudo apt install gcc-10 g++-10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
```
and then `cmake build .`.
it gives error:
```
╭ Tue 06 Dec 18:43:40 ~/vtm vosje@UBUNTU -<
╰─> cmake --build .                                                                                                                        (master)
[ 50%] Building CXX object CMakeFiles/vtm.dir/vtm.cpp.o
make[2]: /usr/bin/c++: Command not found
make[2]: *** [CMakeFiles/vtm.dir/build.make:63: CMakeFiles/vtm.dir/vtm.cpp.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/vtm.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
my system is ubuntu on wsl.
i know there is a windows version, but i am trying to get this to work for linux to install it on my server.

**Comment by o-sdn-o** [comment]
Hi! Probably you need to create a symbolic link with name `/usr/bin/c++` to `/usr/bin/g++`.

**Comment by o-sdn-o** [comment]
> also, are the binaries outdated, or are they just missing the configs. and if they are missing the configs, where do i get them from?

If I understand correctly, vtm has no dependencies other than the C++ compiler.

**Comment by o-sdn-o** [comment]
Oh, you must configure cmake before you run `cmake build .`

```
cmake ./src -DCMAKE_BUILD_TYPE=Release
cmake build .
```

**Comment by Vosjedev** [comment]
i did run `cmake ./src -DCMAKE_BUILD_TYPE=Release`, but i will try the symlink later. thanks!

**Comment by o-sdn-o** [comment]
You may also need to update cmake, perhaps this problem is related to it. I have never encountered such behavior

```bash
sudo apt purge --auto-remove cmake
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null

#a. For Ubuntu Focal Fossa (20.04)
#sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'     

#b. For Ubuntu Bionic Beaver (18.04)
#sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

#c. For Ubuntu Xenial Xerus (16.04)
sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'

#for all
sudo apt update
```

**Comment by o-sdn-o** [comment]
vtm and config can just be copied.
