### ISSUE TITLE
[UI] Animation freezes when timer counter overflows (int32, milliseconds since last reboot)

### ISSUE THREAD

**Issue by thepheer** [netxs-group/vtm#173]
Had no issues building it on aarch64 but encountered a minor bug: some buttons stuck in hover state (see the attached gif).

The bug appears only on my remote aarch64 server:
```
$ uname -a
Linux instance-20211022-2042 5.11.0-1021-oracle #22~20.04.1-Ubuntu SMP Fri Oct 22 21:42:24 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

I've tried to build it locally and it seems to work just fine:
```
$ uname -a
Linux pc 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

vtm and gcc versions on both machines:
```
$ vtm -h
Monotty Desktopio v0.5.9999j

$ gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
```

Will provide more info if needed. Impressive software btw! 👍 

![WindowsTerminal_2vKsL2fUm0](https://user-images.githubusercontent.com/5144598/152998230-c526f293-5aaf-4a28-ae67-84b0c16f7eda.gif)

**Comment by o-sdn-o** [comment]
This behavior occurs when the system has problems with the timer. This often occurs when the system needs to restart after installing system updates.

**Comment by thepheer** [comment]
Yep, you're totally right, fixed by rebooting. Thanks!

**Comment by o-sdn-o** [comment]
This issue occurs when the operating system needs to restart after updates.

`std::chrono::steady_clock` always returns the same value.
