### ISSUE TITLE
Unicode encoding issues on Windows

### ISSUE THREAD

**Issue by jazzl0ver** [netxs-group/vtm#175]
![image](https://user-images.githubusercontent.com/2444175/153376846-696d55e7-17fa-472b-bf39-c98b01225274.png)
```
Windows [Version 10.0.19042.1466]
```

**Comment by o-sdn-o** [comment]
It looks like the code page is not set to UTF-8. Could it be?

**Comment by o-sdn-o** [comment]
This should help:

```cmd
chcp 65001 && vtm
```

**Comment by jazzl0ver** [comment]
yeah, chcp did the job, thank you! should I create a bat file to run vtm or there's a way to set up unicode by default somewhere in the system properties (didn't find it) ? the screenshot i posted i got after running vtm from inside the archive from windows explorer

**Comment by cmplstofB** [comment]
Note:
Some user building vtm from source code by Visual Studio may get a warning [C4189](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4819?view=msvc-170) from cl.exe and could fail to compile it in a chain reaction; even after set codepage to UTF-8.
One of the solution of this is to add [/utf-8 option](https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170) to cl.exe.

```cmd
chcp 65001
cmake ./src -DCMAKE_BUILD_TYPE=Release "-GVisual Studio 17 2022"
cmake -E env "CXXFLAGS=/utf-8" cmake --build . --config Release
```

**Comment by o-sdn-o** [comment]
Question: Should we support for code pages other than 65001(UTF-8) on Windows?

Encodings popularity (www): https://en.wikipedia.org/wiki/Popularity_of_text_encodings
- UTF-8
- ISO-8859-1 https://ru.wikipedia.org/wiki/ISO_8859-1
- CP437
- Windows-1251
- Windows-1252
- CP850
- CP866

pros:
- Applications and libraries system-wide based on 8.3 names.
- Support for old archives with filenames packed in an environment with national encoding.
- Maintaining compatibility with older applications that have been discontinued by the developer.
- Windows uses national code pages by default.
- CP65001 in the console breaks things if enabled. E.g., .NET sees CP65001 and starts outputting the UTF-8 BOM everywhere, breaking applications that don't even care about the character encoding.

cons:
- The presence of support for legacy text encodings slows down the transition of software to UTF-8 encoding.
- Excessive code base growth
    - See https://en.wikipedia.org/wiki/Windows_code_page
    - See https://learn.microsoft.com/en-us/windows/win32/intl/code-page-identifiers
- Waste of resources for implementation.

pros > cons. I think it needs to be implemented. At least one-byte code pages.

**Comment by o-sdn-o** [comment]
Affected win32 console api functions:

`Set/GetConsoleCP` - Input code page (keyboard and titles only)
- ReadConsole
- ReadConsoleInput
- PeekConsoleInput
- WriteConsoleInput 
- SetConsoleTitle
- GetConsoleTitle
- SetConsoleOriginalTitle
- GetConsoleOriginalTitle

`Set/GetConsoleOutputCP` - Output code page
- WriteConsole
- WriteConsoleOutput
- FillConsoleOutputCharacter
- ReadConsoleOutput 
- ReadConsoleOutputCharacter
