### ISSUE TITLE
[Enhancement] Zoom In/Out on Environment

### ISSUE THREAD

**Issue by rsynnest** [netxs-group/vtm#184]
This is a wonderful piece of software! Complex feature requests always feel flippant, but sharing this idea in case it hasn't come up:

My immediate instinct on using vtm was a need for zoom in/out functionality. I think it would make window management and navigation much nicer. I think `Ctrl+Wheel Up/Down` is a good hotkey, matches common conventions and leaves Shift+Wheel for horizontal scrolling. Ideally this would be usable with mouse in any location, not just Desktop Free Space. Zoom would always apply to the entire UI though, not just to the specific element the mouse is hovering over.

Along the way, or in addition, something like MacOS's "view all open windows" would be really cool:
![macos](https://user-images.githubusercontent.com/4392850/153727062-efeb1187-1da5-42a5-a80c-2ea8d648214b.gif)

**Comment by o-sdn-o** [comment]
I set `Alt+Wheel` for horizontal scrolling because `Shift+Wheel` is reserved by most terminal emulators.

**Comment by o-sdn-o** [comment]
I closed this issue automatically, but if something is not completely done, then feel free to reopen the issue. Thanks again for a good idea and sorry for taking so long to implement.

**Comment by rsynnest** [comment]
Wow nice, looks like a clean implementation too, good stuff! I am not a daily user so there is no obligation to address this issue (or any others for that matter, this is your project after all!). Hope it was fun feature to add, happy coding!
