### ISSUE TITLE
Building on macOS 10.15 Catalina fails

### ISSUE THREAD

**Issue by igorstarki** [netxs-group/vtm#187]
Insattlation on Mac OS 10.15.7
```
cmake --build .                                                          ─╯
[ 50%] Building CXX object CMakeFiles/vtm.dir/vtm.cpp.o
In file included from /Users/user/vtm/src/vtm.cpp:31:
In file included from /Users/user/vtm/src/netxs/apps.hpp:7:
In file included from /Users/user/vtm/src/netxs/ui/controls.hpp:7:
/Users/user/vtm/src/netxs/ui/../console/console.hpp:3630:23: error: 'auto' not
      allowed in function prototype
            bool find(auto test_id)
                      ^~~~
In file included from /Users/user/vtm/src/vtm.cpp:31:
In file included from /Users/user/vtm/src/netxs/apps.hpp:322:
In file included from /Users/user/vtm/src/netxs/apps/term.hpp:7:
/Users/user/vtm/src/netxs/apps/../console/terminal.hpp:1207:27: error: 'auto'
      not allowed in function prototype
            void tab_impl(auto size)
                          ^~~~
/Users/user/vtm/src/netxs/apps/../console/terminal.hpp:1235:44: error: no
      matching member function for call to 'tab_impl'
                if (n > 0) while (n-- > 0) tab_impl<true>(size);
                                           ^~~~~~~~~~~~~~
/Users/user/vtm/src/netxs/apps/../console/terminal.hpp:1236:44: error: no
      matching member function for call to 'tab_impl'
                else       while (n++ < 0) tab_impl<faux>(size);
                                           ^~~~~~~~~~~~~~
4 errors generated.
make[2]: *** [CMakeFiles/vtm.dir/vtm.cpp.o] Error 1
make[1]: *** [CMakeFiles/vtm.dir/all] Error 2
make: *** [all] Error 2
╭─   ~/vtm   master ?4 ─────────────────────────────  1m 22s  21:12:36 ─╮
╰─❯ cmake --install .                                                        ─╯
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "/Users/user/vtm/vtm": No such file or directory.
```

**Comment by o-sdn-o** [comment]
Looks like the C++ compiler needs to be updated.
C++20 allows auto as function parameter type.

What version of compiler are you using?
```
clang --version
```
or
```
gcc --version
```

**Comment by igorstarki** [comment]
@o-sdn-o 
`clang --version                                                          ─╯
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

`clang --version                                                          ─╯
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by o-sdn-o** [comment]
Apple Clang 12.0  was released on 16 September, 2020 - It’s out of date.

For Mac OS 10.15.7 system, Clang 12.4 is available for upgrade. Try to update it

**Comment by o-sdn-o** [comment]
Hmm, 12.0.0 (clang-1200.0.32.29), this is the latest for Mac OS 10.15.7

**Comment by o-sdn-o** [comment]
Perhaps it will be possible to update the compiler in this way.  Unfortunately, I have no way to test this option.  I don't know if the latest version of Clang will work on a 10.15.7 system.

I will try to make compatible changes so the older compiler does not complain, but this will only be a temporary solution.  Sooner or later, language constructs that are not supported by older compilers will be used.

**Comment by o-sdn-o** [comment]
I've made changes to the `dev/sdn` branch and your compiler should no longer complain about it.

Try testing and building the `dev/sdn` branch

```bash
git clone https://github.com/netxs-group/vtm.git && cd ./vtm
git checkout dev/sdn
cmake ./src -DCMAKE_BUILD_TYPE=Release
cmake --build . 
```

**Comment by o-sdn-o** [comment]
Also you can use gcc 11.2.0 `gcc@11` or 10.3 `gcc@10` from home-brew: `brew install gcc` which supports it.
https://formulae.brew.sh/formula/gcc

**Comment by igorstarki** [comment]
@o-sdn-o 
`cmake --build .                                                          ─╯
[ 50%] Building CXX object CMakeFiles/vtm.dir/vtm.cpp.o
[100%] Linking CXX executable vtm
[100%] Built target vtm`

How its launching ?
