### ISSUE TITLE
Implement Brow.sh

### ISSUE THREAD

**Issue by dvwallin** [netxs-group/vtm#190]
Brow.sh (https://www.brow.sh/) should be implemented as a shortcut. Would be nice to have a terminal browser in the basics.

**Comment by o-sdn-o** [comment]
The current (v0.6.0) version of vtm allows you to customize the tile manager profile by defining the `VTM_PROFILE_N` environment variable, N is any literal.

Example
```
VTM_PROFILE_4='"Browsh", "Browsh Browser Title", a("Term", "Browsh Window Title", "browsh")'
```

or instantly
```
export VTM_PROFILE_4='"Browsh", "Browsh Browser Title", a("Term", "Browsh Window Title", "browsh")'; vtm
```

Later I will make vtm menu items configurable via global settings. See #52.
