### ISSUE TITLE
[Term] Configure background colors

### ISSUE THREAD

**Issue by sandikata** [netxs-group/vtm#191]
Hello,

Is it possible background color to be changed to something else (or it's just black)?

Regards,
Rosen Aleksandrov

**Comment by o-sdn-o** [comment]
Hi! So far, the background is hardcoded black and this is a temporary solution. This will be configurable later on. Related to #52

Even while there is no way to configure it, here we can discuss background options - solid filling, ansi-art, gradients, active content, etc. I haven't thought much about it yet, but it still needs to be discussed 🙂

**Comment by sandikata** [comment]
It will be cool to be adaptive depends on text color, as i have now some black text and couldn't be seen.

Regards.

**Comment by o-sdn-o** [comment]
I should clarify what kind of background setting we are talking about.  

- Built-in vtm terminal background
- Inter-window environment background (aka desktop background)

Both settings will be possible.

**Comment by o-sdn-o** [comment]
In release 0.6.2 (`dev/sdn` branch) it became possible to set the background color of the terminal using vt-sequence:
`CSI 28 : _SGR_param_ p` [\[SGR (Select Graphic Rendition) parameters\]](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters)

For example setting a blue background:
`CSI 28 : 44 p` or `CSI 28 : 48 : 2 : 0 : 0 : 255 p`
```bash
printf "\e[28:44p"
# or
printf "\e[28:48:2:0:0:255p"
```

Setting blue background and light cyan foreground:
`CSI 28 : 44 ; 28 : 96 p`
```bash
printf "\e[28:44;28:96p"
```
