### ISSUE TITLE
Copying selected area to clipboard -- doesn't copy into the system clipboard (cannot paste outside of the VTM).

### ISSUE THREAD

**Issue by neoh4x0r** [netxs-group/vtm#215]
Both of these copy text into the internal clipboard.
However, there is no way to copy the text to any program outside of the vtm.

1. LeftDrag + RightClick to select and copy text to internal clipboard
2. Ctrl+MiddleDrag to select area and copy text to internal clipboard

Perhaps the copied text cold be put into the system clipboard as well.

**Comment by o-sdn-o** [comment]
The copied fragment is transferred to the system clipboard using the `OSC 52` VT-command. Perhaps the terminal in which you run vtm does not support `OSC 52`, or this feature is disabled.

**Comment by neoh4x0r** [comment]
> In this case, there is no option for this terminal.

Any terminal using VTE will have issues (since it looks like OSC 52 support was rejected due to security concerns).

**Comment by o-sdn-o** [comment]
We've discussed this a bit here https://github.com/netxs-group/vtm/issues/149#issuecomment-1105633359
