### ISSUE TITLE
Moving slider between panes cause Terminal to duplicate lines.

### ISSUE THREAD

**Issue by neoh4x0r** [netxs-group/vtm#217]
If text in a terminal is too large to be shown in full, and the pane is resized, it will duplicate the lines in the terminal.

This appears to be related to wrap-mode going crazy -- though the pane says only 1 line is shown; if wrap is turned off then the lines are not duplicated.

![2022-05-06_01-27](https://user-images.githubusercontent.com/7200584/167072602-8238c232-6213-4d04-b6da-ab414feb7688.png)
![2022-05-06_01-28](https://user-images.githubusercontent.com/7200584/167072604-258a307f-b67e-4b8c-b391-4635f152d57e.png)

**Comment by o-sdn-o** [comment]
This is for sure a bash issue.
Having a multi line prompt is a nice way to avoid that bug even in bash (c).

- https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1927063
- https://askubuntu.com/questions/1335904/gnome-terminal-bash-line-wrapping-issue
- https://github.com/microsoft/terminal/issues/8401

**Comment by o-sdn-o** [comment]
> though the pane says only 1 line is shown

It's really one line wrapped multiple times -- You can run `cat` right here and check it out. vtm operates with lines in the sense of a paragraph. My interpretation of the lines is slightly different from that in the terminal world, but I think it's more correct.
