### ISSUE TITLE
netxs.online is down

### ISSUE THREAD

**Issue by joehakimrahme** [netxs-group/vtm#235]
It used to be that you had a website at vtm.netxs.online, and users could try out vtm with `ssh vtm@netxs.online`. 
This looks down now.

Any plans on getting it (or something similar) back up?

**Comment by o-sdn-o** [comment]
As soon as it is possible to support it, it will be brought back to life. Perhaps it will be a little different.

One way or another, this project needs a live SSH demo.

For the live SSH-demo to work smoothly, we need five VPS's - to cover the entire world - East/West coast US, Europe, Japan, Australia:
 - one VPS 1024MbRAM/1CPU/10GbSSD(4Gb for swap) (Ubuntu + DNS resolver + vtm Demo)
 - and four VPS: 512MbRAM/1CPU (Ubuntu + vtm Demo)

Five servers are enough to really live SSH from anywhere in the world. This worked great and is well tested by the time.

**Comment by o-sdn-o** [comment]
In addition, we also need some kind of DNS domain.
