### ISSUE TITLE
RTF Copy produces strange output

### ISSUE THREAD

**Issue by Alois-xx** [netxs-group/vtm#264]
When I copy RTF from Windows Terminal  with vtm 0.9.6b and then paste the RTF text to e.g. WinWord or OneNote I do not get the text back.

When I copy e.g. from Windows Terminal colorful text
![grafik](https://user-images.githubusercontent.com/408821/199325026-1b80c09a-0421-4e89-a15c-a8249f4da164.png)

I then get in Winword this back:
![grafik](https://user-images.githubusercontent.com/408821/199325224-c7e39f2a-aaf5-4d3c-9fd4-efa4755b5b38.png)

Similar in OneNote I get at least text and some blue colors back, but not the original RTF text
![grafik](https://user-images.githubusercontent.com/408821/199325603-c2eb12c5-c756-44c3-834f-fd06dc51f079.png)

Wordpad seems to be ok. When I copy the text from Wordpad to somewhere else then it seems to be converted
into something readable. 

But the HTML copy works great. I can live with that. I just wanted to make you of this potential issue aware that your RTF
may be standards compliant, but not in the format some MS applications can work with.

**Comment by o-sdn-o** [comment]
Ok. It is reproducible in MS Word 2016 in my setup

![image](https://user-images.githubusercontent.com/11535558/199343865-7376a2e3-ba54-41b5-a458-d735e2ee4907.png)

**Comment by o-sdn-o** [comment]
Now RTF-pasting works with MS Word as expected (at least for me).

OneNote doesn’t support rich text on the clipboard (it is pasted as plain text). OneNote accepts formatted text in HTML format only.

Could you please confirm that this works as expected?

**Comment by AloisKraus** [comment]
I have tried it. It works now perfectly for Word. 
OneNote always had issues, but HTML is the best choice there which also helps me to get rid of the workaround to copy RTF to WinWord and then back to OneNote.
Outlooks can work with RTF and HTML now also. Thanks a ton that really makes my life easier!

This was the fastest Time2Fix I have ever seen for an issue I have raised.

**Comment by o-sdn-o** [comment]
Thanks again for the feedback!
