### ISSUE TITLE
git log does produce empty output in vtm

### ISSUE THREAD

**Issue by AloisKraus** [netxs-group/vtm#268]
When I do _vtm -r cmd_ and then _git log_ for a github repo I get empty output. It looks like
git hits some corner case when rendering colorized output with keyboard navigation.

**Comment by o-sdn-o** [comment]
Thanks for bug report. It is reproducible in my system. Git launches less.exe and it tries to take a console window handle which is NULL.

**Comment by o-sdn-o** [comment]
Oddly enough, a fake window handle not equal to zero is enough to make things work.

**Comment by o-sdn-o** [comment]
Before merging dev/sdn branch, I need to test this because it's very strange behavior and something else might stop working.

**Comment by o-sdn-o** [comment]
I fixed the issue. Could you check if it works?

**Comment by AloisKraus** [comment]
@o-sdn-o: Works perfectly now. Thanks!
