### ISSUE TITLE
Choose terminal interpreter

### ISSUE THREAD

**Issue by KodzghlyCZ** [netxs-group/vtm#279]
It would be good to be able to specify what interpreter to have in VTM terminal. Either through the terminal configuration itself, or the VTM config file

**Comment by o-sdn-o** [comment]
Hi! Apparently you want to specify a shell running in vtm's built-in terminal. There are several ways:
- From the command line: `vtm -r term _your_shell_`
- Using the `$SHELL=_your_shell_` environment variable (only in POSIX operating systems like linux/bsd)
- Using configuration file `~/.config/vtm/settings.xml` (See #234 for details)

Examples
  - Command line `vtm -r term powershell.exe`
  - Set envvar `export SHELL=bash; vtm`
  - Config file
    ```xml
    <config>
        <menu>
            <selected=Term /> <!-- Set default selected menu item. -->
            <item id=Term label="Your shell label" type=DirectVT title="My shell window title" param="$0 -r term powershell.exe"/>
        </menu>
    </config>

**Comment by KodzghlyCZ** [comment]
Thank you for your response and for making such an amazing software. I really enjoy using it! This is the solution I was looking for.
