### ISSUE TITLE
a titlebar for apps

### ISSUE THREAD

**Issue by Vosjedev** [netxs-group/vtm#294]
Hi! I realy enjoy this project, I am using it to manage my server via ssh.

Could you implement something like a titlebar-window to put apps in? currently i am using configurations like this:
`<item id=htop       label="Htop"       type=DirectVT title="Htop"                  param="$0 -r term htop"             notes=" Interactive process viewer "/>`
to make an app have a titlebar.
I am thinking about a titlebar like the demo-apps, but with a custom terminal-command.
I also encounter some problems when I use this config from the preset in the readme:
`<item id=mc         label="mc"         type=SHELL   title="Midnight Commander"    param="mc"               notes=" run Midnight Commander in its own window "/>`
or for [lfm](https://inigo.katxi.org/devel/lfm/):
```<item id=lfm         label="LFM"         type=DirectVT title="Last File Manager"    param="lfm"               notes=" run Last File Manager in its own window "/>```
It just displays the midnight commander window, and I cant move/resize it. also, some apps using this configuration (like [lfm](https://inigo.katxi.org/devel/lfm/)) start a window, then disapear, and lfm ends up running in the background without a window. using
```<item id=lfm         label="LFM"         type=DirectVT title="Last File Manager"    param="$0 -r term lfm"               notes=" run Last File Manager in its own window "/>``` fixes this.

Thanks!

**Comment by o-sdn-o** [comment]
Hi! Thanks for feedback!

> I also encounter some problems when I use this config from the preset in the readme:
> `<item id=mc label="mc" type=SHELL title="Midnight Commander" param="mc" notes=" run Midnight Commander in its own window "/>`

UI controls (top/bottom bar + menu) that allow you to drag the window are provided by the built-in vtm terminal. They are only present (and work) if your application is running on top of the built-in vtm terminal that using DirectVT, like the following:
- `type=DirectVT param="$0 -r term _your_app_executable_path_"`.

Next, `type=SHELL` is used to run `param='command'` on top of the default system shell. So, the following entries will be equivalent:
- `type=SHELL param='mc'`
- `type=ANSIVT param='bash -i mc'`

In this case, there will be no UI controls from the vtm side.

`type=DirectVT` can only be used to run applications that support the DirectVT protocol (protocol is not documented yet). In the example, applications are launched on top of the built-in vtm terminal (which supports this terminal protocol). E.g., `type=DirectVT param="$0 -r term mc"`. Here `$0` will be replaced with the path to the current `vtm` instance.

The following entries will be suitable for your config:
- `<item id=mc label="mc" type=DirectVT title="Midnight Commander" param="$0 -r term mc" notes=" run Midnight Commander in its own window "/>`
- `<item id=lfm label="LFM" type=DirectVT title="Last File Manager" param="$0 -r term lfm" notes=" run Last File Manager in its own window "/>`

P.S.: I need to update the readme.

**Comment by o-sdn-o** [comment]
> Could you implement something like a titlebar-window to put apps in? currently i am using configurations like this:
> <item id=htop label="Htop" type=DirectVT title="Htop" param="$0 -r term htop" notes=" Interactive process viewer "/>
to make an app have a titlebar.

Good idea, I'll add a `type=` that has a draggable title, or just make an additional option to make the title draggable.

**Comment by o-sdn-o** [comment]
I'm currently implementing a configuration merge. This is when the DirectVT application receives a config patch at startup, this is the `config` subparameter inside `item`

```xml
<item ...>
     <config>
         <term>
             ...
         </term>
     </config>
</item>
```

When I'm done, you can say something like

```xml
<item ...>
    <config>
        <term>
            <selection mode=none/>
        </term>
    </config>
</item>
```

In this case, the window can be dragged with the mouse using its entire surface.

**Comment by Vosjedev** [comment]
Nice! I think sometimes dragging a window using it's entire surface is not practical, but realy like the `type=TITLEBAR` idea. I guess I need to learn python now, so I can develop apps for your DE.😀

**Comment by o-sdn-o** [comment]
I'm thinking of changing the DirectVT/ANSIVT/SHELL concept to make it easier and clearer than it is now.  Each option will have a built-in terminal menu that can be customized.

**Comment by o-sdn-o** [comment]
It should be like

SHELL=ANSIVT with prefix ‘bash -c ’ to ‘param’s value.

ANSIVT=DirectVT with prefix ‘$0 -r term ’ to ‘param’s value.

**Comment by o-sdn-o** [comment]
After these changes, the need for a titlebar will probably disappear.  It will have to be tested.

**Comment by o-sdn-o** [comment]
@Vosjedev Now you can specify your own menu for the built-in terminal. See #304 for reference. Could you please check if this approach closes the titlebar issue?

`~/.config/vtm/settings.xml`:
```xml
<config>
    <menu selected=Term>
        <item*/>         <!-- Remove default item records. -->
        <item id=Term>   <!-- title=id type=SHELL param=os_default_shell by default-->
            <config>
                <term>
                    <menu> <!-- Menu with one item -->
                        <item*/> <!-- Zeroize existing menu. -->
                        <item label="ls /bin" action=TerminalSendKey data="ls /bin\n"/>
                    </menu>
                </term>
            </config>
        </item>
        <item id=htop label="htop" type=DirectVT param="$0 -r term htop" notes=" run htop ">
            <config>
                <term>
                    <menu> <!-- Empty menu -->
                        <item*/> <!-- Zeroize existing menu. -->
                    </menu>
                </term>
            </config>
        </item>
        <item id=lfm label="LFM" type=DirectVT title="Last File Manager" param="$0 -r term lfm" notes=" run Last File Manager in its own window "/>
        <autorun*/> <!-- Zeroize default autoruns. -->
    </menu>
</config>
```

**Comment by o-sdn-o** [comment]
I close the issue. Please feel free to reopen if the problem still exists.
