### ISSUE TITLE
keyboard shortcut escape sequence

### ISSUE THREAD

**Issue by Sertonix** [netxs-group/vtm#315]
Sometimes keyboard shortcuts are interpreted by vtm but should effect the open app (eg. terminal).
A keyboard shortcut to prevent the next from being used by vtm would be nice.
Then everything should be possible.

**Comment by o-sdn-o** [comment]
Of course this could be done in the same way as it is done in tmux - Ctrl-b as the main tmux command binding, but I want to come up with a way to completely transfer keyboard focus to an application (or a focused group of applications) and return it using the Host-key or some kind of window menu button, like it is done by virtual machine managers, e.g. VirtualBox reserves the right Ctrl key.

This is related to #86. I haven't dived deep into this issue or experimented with it. The final way to escape the keyboard depends on the ability to support keyboard protocols in modern terminal emulators. There is an option to completely intercept keyboard input at the OS level (Win32/X11/Wayland), handle keypresses/keyreleases, intercept special keys/combinations - e.g. Win+Key, Alt+Tab, etc. In this case, we will have complete freedom to choose the option to control keyboard input.

At the moment, I'm thinking of implementing the following keyboard input processing scheme:

- vtm runs locally and interacting directly with Win32/X11/Wayland (in the future it will also render itself in GUI) intercepts all keyboard input. For example, this is how vtm clipboard support works in Win32 now #273.
- The local vtm instance, using its own keyboard protocol, exchanges keyboard events with other local and remote (via SSH) vtm instances, including DirectVT apps.

**Comment by o-sdn-o** [comment]
Closing in favor of #86
