### ISSUE TITLE
server config

### ISSUE THREAD

**Issue by Sertonix** [netxs-group/vtm#321]
The current config only has an effect on the client.

Currently the only option I know of would be the pipe used for the cunnection.
But I think there could be more options in the future like preventing clients from shuting down the server.

**Comment by o-sdn-o** [comment]
Of the server configuration options, so far there are only appearance configuration, color scheme and fps. This is in the <config/appearance> section.

```xml
    <appearance>
        <defaults>
            <fps      = 60   />
            <bordersz = 1,1  />
            <brighter = 60   />
            <kb_focus = 60   />
            <shadower = 180  />
            <shadow   = 180  />
            <lucidity = 0xff /> <!-- not implemented -->
            <selector = 48   />
            <highlight  fgc=purewhite bgc=bluelt      />
            <warning    fgc=whitelt   bgc=yellowdk    />
            <danger     fgc=whitelt   bgc=redlt       />
            <action     fgc=whitelt   bgc=greenlt     />
            <label      fgc=blackdk   bgc=whitedk     />
            <inactive   fgc=blacklt   bgc=transparent />
            <menu_white fgc=whitelt   bgc=0x80404040  />
            <menu_black fgc=blackdk   bgc=0x80404040  />
            <fader duration=0ms fast=0ms/>  <!-- Fader animation config. -->
        </defaults>
        <runapp>    <!-- Override defaults. -->
            <brighter=0/>
        </runapp>
    </appearance>
```

**Comment by Sertonix** [comment]
I haven't tested it but it should be possible to start the client and server with with different configs.
Seperating the configs in the config file would then make it more obvious which are used.

Also only a bit related. Is there some way to connect through ssh but use the client config from the current computer?

**Comment by o-sdn-o** [comment]
> Is there some way to connect through ssh but use the client config from the current computer?

Theoretically, this is possible. If a DirectVT application is launched remotely via SSH from a locally launched vtm environment, then a copy of the configuration from the </config/menu/item/config> parameter will be transferred and merged to remote app. I haven't experimented with this use case yet. There, it may be necessary to modify the DirectVT protocol for such a scenario.

**Comment by o-sdn-o** [comment]
I found a small inconsistency. The client, when starting a new server, does not transfer to it the configuration received via the DirectVT protocol.

**Comment by o-sdn-o** [comment]
I have to re-implement the server startup and the way the configuration is passed to it. The way it's done now is not correct.

**Comment by o-sdn-o** [comment]
FYI, Since release v0.9.8o vtm supports DirectVT over SSH. If <config/menu/item/config> is specified, it is directly passed to the remote instance as the running configuration. The server part inherits the client configuration when automatically launched (as a result of the client process fork).

Note. SSH connection requires key-based authentication (w/o password protection) to avoid interactivity. The -q option is also very desirable to exclude any text messages from the ssh-client that break the DirectVT binary protocol.

Example
```xml
<item id="vtm over ssh" type=DirectVT param="ssh -q -i ./authkey user@server vtm">
  <config>
    <client>
      <background fgc=whitedk bgc=bluedk/>
    </client>
  </config>
</item>
```
