### ISSUE TITLE
scoped navigation lines

### ISSUE THREAD

**Issue by Sertonix** [netxs-group/vtm#325]
It would be nice if all windows inside a view would have there navigation lines hidden by default.
Only if view is visible on the screen the lines should be shown.
This would make reduce the amount of navigation lines shown at once and therefore ease navigation.

In addition to this could be that the navigation lines to views show some text so that you can easily identify them.

**Comment by o-sdn-o** [comment]
> In addition to this could be that the navigation lines to views show some text so that you can easily identify them.

Need to add tooltips there.
