### ISSUE TITLE
--version not implemented

### ISSUE THREAD

**Issue by thisismygitrepo** [netxs-group/vtm#351]
Can I ask you to please implement `--version` just like any other cli app?
Its breaking my code by not conforming to this norm.
Thanks

**Comment by thisismygitrepo** [comment]
At the moment, I'm getting this thing for reference

```
vtm --version
 vtm: v0.9.8n
  os: unknown option '--version' (187)

Terminal multiplexer with window manager and session sharing.
```
and then a long list of how to use it, that looks like `--help` :/
not sure what's happening there.

**Comment by o-sdn-o** [comment]
Thanks for the report. I will fix this inconsistency.
