### ISSUE TITLE
Demo apps do not work after vtm/desktopio split

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [netxs-group/vtm#357]
Text and Calc just freezes the terminal.

**Comment by o-sdn-o** [comment]
I fixed it. The frame rate adjustment mechanism blocks writing to the buffer until it is empty, and this results in a deadlock if the reading loop has not been started.

**Comment by o-sdn-o** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Thanks for testing it.
