### ISSUE TITLE
WindowsPowerShell vs Powershell

### ISSUE THREAD

**Issue by mathematician001** [netxs-group/vtm#368]
I think there is lack of distinction between the two in this utility, can we please have them separated? Namely, in the `settings.xml` file. Although names of executables are counterintuitive.

`powershell.exe` launches WindowsPowerShell (Microsoft developed).
`pwsh.exe` launches PowerShell (community developed).

**Comment by o-sdn-o** [comment]
Thanks for the note! I changed the tooltip text and default window title to "Windows PowerShell".

![image](https://user-images.githubusercontent.com/11535558/233764820-f2854aa5-e383-48d7-ad4a-20466be4a9a2.png)
