### ISSUE TITLE
vtm not respecting the settings file located in default path

### ISSUE THREAD

**Issue by mathematician001** [netxs-group/vtm#370]
I'm on a windows machine and `vtm` doesn't respect the settings file located @ `~/.config/vtm/settings.xml` (its actually a symlink to somewhere else).

I had to explitictly pass the path with `-c` option.
With experiments, I realized that the problem is potentially **not** expanding the tilde in the path. Even with `-c` option and explicit path passing, it fails if there was a `~` in the path, I have to pass home directory explicitly.

Can we please fix, at least the default path bug?

**Comment by o-sdn-o** [comment]
Certainly this should be fixed. Thanks for the feedback.

In the current implementation, a path containing `~` is expanded using the `HOMEDRIVE` and `HOMEPATH` environment variables. This checks only for the presence of `~/` characters at the beginning of the path. A more generic `~` expansion needs to be implemented there, including for the `\ ` character.

**Comment by o-sdn-o** [comment]
I removed the dependency on environment variables when detecting the path to the user profile. Could you test this on the `dev/sdn` branch (or see precompiled binary at https://github.com/netxs-group/vtm/releases/tag/v0.9.9f)?

**Comment by mathematician001** [comment]
It works 👌
Thanks for the quick response.
