### ISSUE TITLE
[feature request] app window minimization

### ISSUE THREAD

**Issue by Fan-iX** [netxs-group/vtm#376]
Hello, I've been using vtm for a few months, and I really enjoy it.

I think it would be useful to have a app window minimization feature, which may help when having a lot of windows.
Maybe we can have a minimization button in the menu bar, and click on the taskbar item to restore.

Thanks!

**Comment by o-sdn-o** [comment]
Ok, I need to think about where to put the minimized window.

FYI now we can simply drag the window off the screen with a quick Ctrl+MouseDrag. In this case, the window flies out of the viewport and can be returned back through the menu using the RightClick.

**Comment by o-sdn-o** [comment]
I want to try to make minimization by right click on the window menu.  The window should collapse vertically into a horizontal stripe.

**Comment by o-sdn-o** [comment]
Now it looks like this

https://github.com/netxs-group/vtm/assets/11535558/a58b9de1-44e3-4bf9-8670-53bfec86f860

**Comment by o-sdn-o** [comment]
Interesting UX with tiling manager

https://github.com/netxs-group/vtm/assets/11535558/d11b745f-8685-4147-9bf2-8934416ba49c
