### ISSUE TITLE
How to make a static build

### ISSUE THREAD

**Issue by Fan-iX** [netxs-group/vtm#378]
I want to run vtm on a server with a old version of `libc.so` only (`GLIBC==2.31`).
The binary release `0.9.9h` does not work since it requires `GLIBC>=2.34`

```
./vtm: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./vtm)
./vtm: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./vtm)
./vtm: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./vtm)
```

I do not have root access to that server, so I'm not able to update `libc.so` there.
Instead, I tried to build a static version of vtm in my local WSL environment.

First I uncommented the line in `vtm/src/CMakeLists.txt`

```
        set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libstdc++ -static-libgcc -pthread -s")
```

then I ran

```
cmake ./src
cmake --build .
```

However, the built executable still requires `libc.so`:

```
ldd ./vtm
        linux-vdso.so.1 (0x00007ffff454c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91951c0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9194f90000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9195c95000)
```

and still fails to launch on that server.

I tried both `master` and `dev/sdn` branch, and neither of them worked.

Is it possible to build a static `vtm` executable without `libc.so.6` requirement?

**Comment by o-sdn-o** [comment]
Looks like the `-static` parameter is missing. I updated `CMakeLists.txt`/`CMakeSettings.json`.

**Comment by Fan-iX** [comment]
It works now.
Thank you!
