### ISSUE TITLE
Add an option to disable cursor highlight on menu bar

### ISSUE THREAD

**Issue by Fan-iX** [netxs-group/vtm#379]
I am using a font with ligature feature (Cascadia Code PL) in Windows Terminal.

It seems that the ligature feature only works for characters having the same background and foreground colors.

So the text "icon" layout of the menu bar changes when the cursor moves near, due to the highlight effect.

![vtm-with-ligature-font](https://github.com/netxs-group/vtm/assets/61686936/184b02d9-94d4-4eb2-bb84-74cc7de1f499)

Could you provide an option to disable the cursor highlight effect on the menu bar?

**Comment by o-sdn-o** [comment]
I will add this option.

**Comment by o-sdn-o** [comment]
The following global option to enable/disable mouse cursor highlighting (default is on)
```xml
<config>
  <appearance>
    <defaults>
      <tracking = on/>
    </defaults>
  </appearance>
</config>
```
