### ISSUE TITLE
More window controls

### ISSUE THREAD

**Issue by Golem642** [netxs-group/vtm#396]
Hello, I'd like to suggest some things about the applications window :
- [x] A minimize button (so we don't have every app at the same time on the desktop)
When minimized, the application will still be visible in the taskbar so I also suggest adding
- [x] A taskbar collapse button (for each application that has at least one window open, a collapse button appears on the right of the application's name on the taskbar so it can hide away all of the open windows and not pollute when you have too many of them open at the same time)
- [x] Maybe move the fullscreen button next to the close button (and the new minimize button ?)
- [x] A setting which allows you to choose where you want to place the close/minimize/maximize buttons
- [x] A "smart wrap" option on the windows where instead of wrapping using characters, it wraps using words

That's it for now i guess, tell me what you think !

**Comment by o-sdn-o** [comment]
Thanks for your thoughts.

> A minimize button (so we don't have every app at the same time on the desktop)
When minimized, the application will still be visible in the taskbar so I also suggest adding a taskbar collapse button

Our UI already has a sort of minimize feature (right click on the window menu) and you are asking for the window to be completely hidden on the desktop, but leaving an active reference to it on the taskbar. We definitely need to add this functionality.

> for each application that has at least one window open, a collapse button appears on the right of the application's name on the taskbar so it can hide away all of the open windows and not pollute when you have too many of them open at the same time

I agree. This is useful feature.

> Maybe move the fullscreen button next to the close button (and the new minimize button ?)

There is a big risk of accidentally closing the window, especially when using the touchpad. Although in all window environments they group window manipulation buttons. Here we need to think, play with the buttons and test additionally.

> A setting which allows you to choose where you want to place the close/minimize/maximize buttons

We can add the base window menu template to the configuration as the basis for all running applications. Users will be able to modify the default menu layout by editing this template.

> A "smart wrap" option on the windows where instead of wrapping using characters, it wraps using words

We have many places where char-by-char (even cell-by-cell) wrapping occurs. Perhaps it is better for us to open a separate issue for each specific case
- Window titles and footers (currently is char based)
- Taskbar items, Buttons and Text labels inside windows (currently is cell based)
- Terminal scrollback (unrealistic to change behavior)

**Comment by o-sdn-o** [comment]
I added Minimize/Maximize/Close buttons to the top right corner of the window. It is also now possible to minimize a window by left-clicking on the window reference in the taskbar.


https://github.com/netxs-group/vtm/assets/11535558/f575c85a-9d85-4777-8422-0478b7ca8640

**Comment by o-sdn-o** [comment]
I've added a global option to select the location of the window control buttons: `config/appearance/defaults/macstyle`.





https://github.com/netxs-group/vtm/assets/11535558/fa2f0879-1fcb-4124-9a15-6cd71ca833f0

**Comment by Golem642** [comment]
That's great ! People from Mac won't be lost, and everybody can find themselves

**Comment by o-sdn-o** [comment]
I decided to implement word-based wrapping everywhere except the terminal:

https://github.com/netxs-group/vtm/assets/11535558/bbfb7129-ea6d-44cf-95bb-1c3548ae0c89

**Comment by Golem642** [comment]
Awesome ! Text will look less weird in applications.
I don't have any more suggestions for now, so might as well close this once the next version is out. I'll reopen if there are new ideas, which anyone can suggest btw !

**Comment by Golem642** [comment]
You really are rocking this seriously o-sdn-o, awesome app with an awesome developer 👍

**Comment by o-sdn-o** [comment]
Thank you for your kind words!
