### ISSUE TITLE
Latest release (0.9.9v) detected as malware (false-positive)

### ISSUE THREAD

**Issue by Golem642** [netxs-group/vtm#432]
https://www.virustotal.com/gui/file/c8c7e95d4369db60ac222feddb698ca47ab4ecc019e72674eeca77728c35d231/detection
My windows defender blocked it, i know it's probably a false alarm so maybe there is a function that makes them think like that

**Comment by o-sdn-o** [comment]
I regularly report such false positives from Windows Defender to Microsoft support; they detect signatures in about 12 hours. I was in a hurry this time and didn't check, sorry. I have now reported this false positive. For some reason these are always 32-bit binaries. Thanks for your feedback.

**Comment by o-sdn-o** [comment]
I uploaded a new release `v0.9.9v (fixed terminal)`. An annoying bug has been fixed there. And it is also false-positively detected (for Intel 32-bit Windows). I reported to Microsoft. They will fix the signatures a little later just like the previous release (8-12 hours).

**Comment by Golem642** [comment]
> I uploaded a new release `v0.9.9v (fixed terminal)`. An annoying bug has been fixed there

Oh and also i saw that the wide option for the menu is bugged when turned on : the text doesn't align in the middle and instead stays stuck to the top left

**Comment by o-sdn-o** [comment]
I will fix it.
