### ISSUE TITLE
Disable double click toggling window maximization for tui apps with mouse support

### ISSUE THREAD

**Issue by Fan-iX** [netxs-group/vtm#438]
Newer versions of `vtm` always toggle window maximization on double click, so I can't use double click normally in some tui applications (such as `vim` with mouse support, or `nnn`)
Older versions (at least in `v0.9.9h`) do not show this behavior

**Comment by o-sdn-o** [comment]
I fixed this issue and you can download a new binary from https://github.com/netxs-group/vtm/pull/437/checks (Artifacts submenu) to test it.
