### ISSUE TITLE
client cannot be killed by `SIGTERM`

### ISSUE THREAD

**Issue by Fan-iX** [netxs-group/vtm#452]
Client can no longer be killed by `SIGTERM` in recent versions of `vtm`.

I suppose several issues are related with this behavior:
1. recursive connection (`vtm` in `vtm`) cannot be closed
2. client opened in a ssh shell won't be closed automatically when `ssh` connection is down

vtm version: v0.9.14

![image](https://github.com/netxs-group/vtm/assets/61686936/7ff1ca55-b2a6-4d48-9931-5735dd4f35c3)

**Comment by o-sdn-o** [comment]
Running server also blocks system shutdown/reboot. Terrible flaw.

**Comment by o-sdn-o** [comment]
I fixed the platform signal handling. Could you please check this?

**Comment by Fan-iX** [comment]
That branch works fine in Linux. Thank you.
