### ISSUE TITLE
Crashes on Windows 11

### ISSUE THREAD

**Issue by coltonisgod234** [netxs-group/vtm#462]
i installed with scoop and i got this error:
vtm: v0.9.16
apps: Loading configuration from $VTM_CONFIG...
apps: Loading configuration from ~/.config/vtm/settings.xml...
      No configuration found, try another source
      Fallback to hardcoded configuration
main: New vtm session for Colton Wollinger
  os: Process forked
  os: Connection error (2)
  os: No vtm server connection (2)

can anybody help me?

**Comment by o-sdn-o** [comment]
Hi, there is a problem that it is impossible to connect to vtm by non-elevated user if vtm was previously started by elevated user. I'll fix this soon.
