### ISSUE TITLE
term: Introduce new concept for terminal text layout

### ISSUE THREAD

**Issue by o-sdn-o** [netxs-group/VTM#61]
The current insertion point is calculated incorrectly. VT cursor positioning commands do not work as expected.

**Comment by o-sdn-o** [comment]
Introduce new concept for terminal text layout

During resize, text lines that have the wrap attribute enabled are wrapped over the underlying ones.

`rods`

![terminal_rods_titan2](https://user-images.githubusercontent.com/11535558/106723957-7d7d7b80-6629-11eb-944d-bea6bb3823a8.gif)

It is curious whether this approach is compatible with terminal reality.

**Comment by Nanoc-ice** [comment]
That is an interesting effect if the context in the screen doesn’t wrap.  What would happen if you were editing something in the window, say with vim, and had line wrap on in the editor.  As you change the size of the screen  would vim be the first to wrap, hence leaving nothing to wrap by the terminal?

**Comment by o-sdn-o** [comment]
>  As you change the size of the screen  would vim be the first to wrap, hence leaving nothing to wrap by the terminal?

Almost all full-screen terminal applications do their own wrapping by inserting `\n` or `\e[y;xH`  at the end. These applications keep track of the terminal size changes and redraw the entire screen when resizing.

For example `vim`
![image](https://user-images.githubusercontent.com/11535558/106762939-2cd14700-6658-11eb-9761-bb289fddf94d.png)

When emitting long lines, terminal applications can rely on the terminal, but there is no single approach to wrap lines in terminals:
- Terminals can calculate the length of a string in cells using a different algorithm than the application, and as a result, they do wrapping in a different place where the application suggests
- There is no standard approach to dissecting ligatures and wide characters (Emoji, CJK) at the edge of the screen, although most wraps these characters entirely on a new line, the application cannot know about it in advance

**Comment by o-sdn-o** [comment]
For example `vim` adds `>` + `\e[2;1H` if a wide character is encountered at the end

![image](https://user-images.githubusercontent.com/11535558/106763831-0a8bf900-6659-11eb-905a-4aba0c0421cd.png)

![image](https://user-images.githubusercontent.com/11535558/106764955-20e68480-665a-11eb-997e-ff18fc08f95e.png)

**Comment by o-sdn-o** [comment]
VTM built-in terminal reserves additional screen lines under the long lines when outputting a file with long lines directly

![image](https://user-images.githubusercontent.com/11535558/106767282-820f5780-665c-11eb-8072-e57d78c2a77d.png)

![ezgif-4-971ac8d88100](https://user-images.githubusercontent.com/11535558/106767952-3e691d80-665d-11eb-8007-0bbbd1217ebc.gif)

**Comment by o-sdn-o** [comment]
The most important advantage of such a text layout in the terminal is the correct support for characters larger than one cell

![tall_chars_wrapping](https://user-images.githubusercontent.com/11535558/106778123-737a6d80-6667-11eb-9ce4-913529f32f04.gif)

Ultimately, this is required to support the following functionality
![advanced-terminal-i23](https://user-images.githubusercontent.com/11535558/106778492-db30b880-6667-11eb-8852-bc0f2eee0885.gif)

**Comment by o-sdn-o** [comment]
It is important to note that the process of overlaying lines is _reversible_, i.e. when overlaid, the lines themselves are not mangled, they are only drawn overlaid.

**Comment by o-sdn-o** [comment]
You can control whether the line is wrapped or not using private VT-commands 
-  `CSI 12 : 0 p` disable wrapping (`\e[12:0p`)
-  `CSI 12 : 1 p` enable wrapping (`\e[12:1p`)

![wrapping](https://user-images.githubusercontent.com/11535558/106879244-b76b8200-66fc-11eb-8a01-42e7522664f2.gif)

**Comment by o-sdn-o** [comment]
Apparently, the `rods` concept is quite compatible with the terminal reality.
This can be tested with v0.2.9 release.
